# TokyoNight Night color palette for fish.
# Replaces the default frozen theme generated by fish 4.3 migration.

set --global fish_color_normal c0caf5
set --global fish_color_command 7dcfff
set --global fish_color_keyword bb9af7
set --global fish_color_quote e0af68
set --global fish_color_redirection c0caf5
set --global fish_color_end ff9e64
set --global fish_color_error f7768e
set --global fish_color_param 9d7cd8
set --global fish_color_comment 565f89
set --global fish_color_selection --background=33467c
set --global fish_color_search_match --background=33467c
set --global fish_color_operator 9ece6a
set --global fish_color_escape bb9af7
set --global fish_color_autosuggestion 565f89
set --global fish_color_cancel -r
set --global fish_color_cwd 9ece6a
set --global fish_color_cwd_root f7768e
set --global fish_color_history_current --bold
set --global fish_color_host normal
set --global fish_color_host_remote e0af68
set --global fish_color_status f7768e
set --global fish_color_user 9ece6a
set --global fish_color_valid_path --underline
set --global fish_pager_color_progress 565f89
set --global fish_pager_color_prefix 7dcfff
set --global fish_pager_color_completion c0caf5
set --global fish_pager_color_description 565f89
set --global fish_pager_color_selected_background --background=33467c
